// Icônes optimisées - import individuel pour réduire la taille du bundle
export {
  MessageCircle,
  Send,
  Bot,
  User,
  Sparkles,
  Minimize2,
  Loader2,
  Zap,
  Trophy,
  BookOpen,
  Search,
  ChevronRight,
  ChevronDown,
  ArrowLeft,
  CheckCircle,
  X,
  Settings,
  Home,
  Users,
  BarChart3,
  Calendar,
  FileText,
  Play,
  Pause,
  Volume2,
  VolumeX,
  Eye,
  EyeOff,
  Edit,
  Trash2,
  Plus,
  Minus,
  Star,
  Heart,
  Clock,
  AlertCircle,
  Info,
  Check,
  Mail,
  Phone,
  MapPin,
  Globe,
  Camera,
  Upload,
  Download,
  Share,
  Copy,
  Link,
  ExternalLink,
  RefreshCw,
  RotateCcw,
  Save,
  LogOut,
  User as UserIcon,
  Lock,
  Unlock,
  Shield,
  ShieldCheck,
  AlertTriangle,
  Bell,
  BellOff,
  Moon,
  Sun,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Wifi,
  WifiOff,
  Battery,
  BatteryLow,
  BatteryFull,
  Cpu,
  HardDrive,
  Server,
  Database,
  Cloud,
  CloudRain,
  Zap as Lightning,
  Flame,
  Target,
  Crosshair,
  TrendingUp,
  TrendingDown,
  BarChart,
  PieChart,
  LineChart,
  Activity,
  DollarSign,
  Euro,
  PoundSterling,
  Bitcoin,
  CreditCard,
  Wallet,
  Receipt,
  Calculator,
  Percent,
  Hash,
  AtSign,
  Hash as Number,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Code,
  Heading1,
  Heading2,
  Heading3,
  List,
  ListOrdered,
  Quote,
  Image,
  Video,
  Music,
  File,
  Folder,
  FolderOpen,
  Archive,
  Package,
  Box,
  Gift,
  Award,
  Medal,
  Trophy as TrophyIcon,
  Crown,
  Star as StarIcon,
  Heart as HeartIcon,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
  Laugh,
  Angry,
  Surprised,
  Cool,
  Tired,
  Sleep,
  Coffee,
  Beer,
  Wine,
  Pizza,
  Cake,
  Cookie,
  IceCream,
  Apple,
  Banana,
  Carrot,
  Cherry,
  Lemon,
  Orange,
  Strawberry,
  Watermelon,
  Grapes,
  Peach,
  Pineapple,
  Kiwi,
  Mango,
  Pear,
  Plum,
  Cherry as CherryIcon,
  Lemon as LemonIcon,
  Orange as OrangeIcon,
  Strawberry as StrawberryIcon,
  Watermelon as WatermelonIcon,
  Grapes as GrapesIcon,
  Peach as PeachIcon,
  Pineapple as PineappleIcon,
  Kiwi as KiwiIcon,
  Mango as MangoIcon,
  Pear as PearIcon,
  Plum as PlumIcon,
  Car,
  Bus,
  Train,
  Plane,
  Bike,
  Walk,
  Navigation,
  Map,
  MapPin as MapPinIcon,
  Compass,
  Anchor,
  Ship,
  Truck,
  Tractor,
  Ambulance,
  FireTruck,
  Police,
  Hospital,
  School,
  Church,
  Castle,
  Building,
  Factory,
  Warehouse,
  Store,
  ShoppingCart,
  ShoppingBag,
  CreditCard as CreditCardIcon,
  Wallet as WalletIcon,
  Receipt as ReceiptIcon,
  Calculator as CalculatorIcon,
  DollarSign as DollarSignIcon,
  Euro as EuroIcon,
  PoundSterling as PoundSterlingIcon,
  Bitcoin as BitcoinIcon,
  Landmark,
  PiggyBank,
  Banknote,
  Coins,
  Gem,
  Diamond,
  Crown as CrownIcon,
  Award as AwardIcon,
  Medal as MedalIcon,
  Trophy as TrophyIcon2,
  Star as StarIcon2,
  Heart as HeartIcon2,
  ThumbsUp as ThumbsUpIcon,
  ThumbsDown as ThumbsDownIcon,
  Hand,
  Fist,
  Peace,
  Rock,
  Paper,
  Scissors,
  Gamepad2,
  Headphones,
  Microphone,
  Speaker,
  Radio,
  Tv,
  Monitor as MonitorIcon,
  Smartphone as SmartphoneIcon,
  Tablet as TabletIcon,
  Laptop as LaptopIcon,
  Mouse,
  Keyboard,
  Printer,
  Usb,
  Hdmi,
  Wifi as WifiIcon,
  WifiOff as WifiOffIcon,
  Bluetooth,
  Battery as BatteryIcon,
  BatteryLow as BatteryLowIcon,
  BatteryFull as BatteryFullIcon,
  Plug,
  Power,
  Lightbulb,
  Flashlight,
  Sun as SunIcon,
  Moon as MoonIcon,
  Cloud as CloudIcon,
  CloudRain as CloudRainIcon,
  CloudSnow,
  CloudLightning,
  Umbrella,
  Snowflake,
  Wind,
  Thermometer,
  Droplets,
  Flame as FlameIcon,
  Fire,
  Zap as ZapIcon,
  Lightning as LightningIcon,
  Activity as ActivityIcon,
  TrendingUp as TrendingUpIcon,
  TrendingDown as TrendingDownIcon,
  BarChart as BarChartIcon,
  PieChart as PieChartIcon,
  LineChart as LineChartIcon,
  Target as TargetIcon,
  Crosshair as CrosshairIcon,
  Cpu as CpuIcon,
  HardDrive as HardDriveIcon,
  Server as ServerIcon,
  Database as DatabaseIcon,
  Cloud as CloudIcon2,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  Shield as ShieldIcon,
  ShieldCheck as ShieldCheckIcon,
  AlertTriangle as AlertTriangleIcon,
  Bell as BellIcon,
  BellOff as BellOffIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Edit as EditIcon,
  Trash2 as Trash2Icon,
  Plus as PlusIcon,
  Minus as MinusIcon,
  Check as CheckIcon,
  X as XIcon,
  RefreshCw as RefreshCwIcon,
  RotateCcw as RotateCcwIcon,
  Save as SaveIcon,
  LogOut as LogOutIcon,
  Settings as SettingsIcon,
  Home as HomeIcon,
  Users as UsersIcon,
  BarChart3 as BarChart3Icon,
  Calendar as CalendarIcon,
  FileText as FileTextIcon,
  Play as PlayIcon,
  Pause as PauseIcon,
  Volume2 as Volume2Icon,
  VolumeX as VolumeXIcon,
  Mail as MailIcon,
  Phone as PhoneIcon,
  MapPin as MapPinIcon2,
  Globe as GlobeIcon,
  Camera as CameraIcon,
  Upload as UploadIcon,
  Download as DownloadIcon,
  Share as ShareIcon,
  Copy as CopyIcon,
  Link as LinkIcon,
  ExternalLink as ExternalLinkIcon,
  Clock as ClockIcon,
  AlertCircle as AlertCircleIcon,
  Info as InfoIcon,
  Search as SearchIcon,
  ChevronRight as ChevronRightIcon,
  ChevronDown as ChevronDownIcon,
  ArrowLeft as ArrowLeftIcon,
  Minimize2 as Minimize2Icon,
  Loader2 as Loader2Icon,
  Sparkles as SparklesIcon,
  BookOpen as BookOpenIcon,
  Bot as BotIcon,
  MessageCircle as MessageCircleIcon,
  Send as SendIcon,
  User as UserIcon2,
  Zap as ZapIcon2,
  Trophy as TrophyIcon3,
  CheckCircle as CheckCircleIcon
} from 'lucide-react';
